logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
accesslog = "" # http access log file
addr = "0.0.0.0:443"
addrext = "https://0.0.0.0:443/"
certpem = "auto"
staticdir = "/static"
staticprefix = "/static"
staticcachecontrol = "max-age=31968000, s-maxage=864000, stale-while-revalidate=86400, public"
detailprefix = "/detail"
updateprefix = "/update"
searchprefix = "/search"
imagesearchprefix = "/images"
collectionsprefix = "/collections"
collectionscatalog = "HGK Collections"
apiprefix = "/api"
jwtalg = ["HS256","HS384","HS512"]
linktokenexp = "1h"
idletimeout = "30m"
usercachesize = 200
mediaserverkey = "swordfish"
mediaserverexp = "6h"
ampcache = ""
ampapikey = "private-key.pem"
cachedir = "./cache"
clearcacheonstartup = true # remove badger files from cachedir
templatedev = true

[prefix]
    detail = "/detail"
    update = "/update"
    search = "/search"
    collections = "/collections"
    cse = "/cse"
    cluster = "/cluster"
    api = "/api"
    static = "/static"
    sitemap = "/sitemap"
    images = "/images"

[google]
    apikey = ""
    apikey2 = ""
