logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
staticdir = "C:/temp/sitemap"
sitemapprefix = "catalogue"
addrext = "https://localhost:443/"
sleep = "1m"

clearbeforesync = [
    ## 2553473, # HGK Publikationen
    ## 2514673, # rimab
    ## 2171465, # basle_bibliography_for_historical_performance_practice
    ## 2512784, # HGK Events
    ## 2476895, # irf
    # 2612786, # lernen

    2206003, # ACT Basel  // indexer - not yet implemented
    1510020, # Institut Industrial Design / Thesen
    2486551, # ACT 2020
    2483850, # Albena
    2317722, # archive_des_ephemeren
    2474728, # armin
    2561875, # company_cultures__leitbilder
    2327162, # digitalbrainstorming
    2260611, # digitale see
    2605562, # erinnerungsraum
    2329831, # HGK Fotoarchiv
    2250437, # Grenzgang
    704562,  # Handapparate
    2545256, # HGK Collections
    2570300, # hphuser_import
    1510019, # Hyperwerk
    2571475, # IKUVID
    2315925, # Masterstudio / Thesen
    2608921, # Institut Kunst
    1510009, # Institut Kunst intern
    1510034, # institut_mode_design
    2571213, # SIK interviews archiv performativ
    2009066, # invar
    2358931, # julia
    2582183, # julia_2020
    2634291, # knstlerinnen
    2608904, # panch
    2497586, # pascale_grau
    1624911, # pcb_basel
    2604593, # Peter von Arx
    2488157, # Kasko digital
    2068924, # summe2017
    2559823, # videowochen_im_wenkenpark
    2579176, # Wissenscluster
    # 2758283, # Applied Fine Performaing Arts
    # 2857696, # Doce en Diciembre
    # 2910166, # Kasko Memoriav
    4278174, # Institut Mode-Design Web
    2758283, # applied_fine_performaing_arts
    4371987, # makesense admin
    # 2641719, # werke
]

groups = [
    ## 2553473, # HGK Publikationen
    ## 2514673, # rimab
    ## 2171465, # basle_bibliography_for_historical_performance_practice
    ## 2512784, # HGK Events
    ## 2476895, # irf
    ## 2612786, # lernen

    #  1510020, # Institut Industrial Design / Thesen
    #  2206003, # ACT Basel  // indexer - not yet implemented
    #  2486551, # ACT 2020
    #  2483850, # Albena
    #  2317722, # archive_des_ephemeren
    #  2474728, # armin
    #  2561875, # company_cultures__leitbilder
    #  2327162, # digitalbrainstorming
    #  2260611, # digitale see
    #  2605562, # erinnerungsraum
    #  2329831, # HGK Fotoarchiv
    #  2250437, # Grenzgang
    #  704562,  # Handapparate
    #  545256, # HGK Collections
    #  2570300, # hphuser_import
    #  1510019, # Hyperwerk
    #  2571475, # IKUVID
    #  2315925, # Masterstudio / Thesen
    #  2608921, # Institut Kunst
    #  1510009, # Institut Kunst intern
    #  1510034, # institut_mode_design
    #  2571213, # SIK interviews archiv performativ
    #  2009066, # invar
    #  2358931, # julia
    #  2582183, # julia_2020
    #  2634291, # knstlerinnen
    #  2608904, # panch
    #  2497586, # pascale_grau
    #  1624911, # pcb_basel
    #  2604593, # Peter von Arx
    #  2488157, # Kasko digital
    #  2068924, # summe2017
    #  2559823, # videowochen_im_wenkenpark
    #  2579176, # Wissenscluster
    #  2758283, # Applied Fine Performaing Arts
    #  2857696, # Doce en Diciembre
    #  2910166, # Kasko Memoriav
    #  4278174, # Institut Mode-Design Web
    #  2758283, # applied_fine_performaing_arts
    #  4371987, # makesense admin
    2641719, # werke
]

fairgroups = [
    # 704562,  # Handapparate
    2608904, # panch
    2641719, # werke
    2571213, # SIK interviews archiv performativ
    2260611, # digitale see
    2608904, # panch
    1624911, # pcb_basel
    2317722, # archive_des_ephemeren
    4278174, # Institut Mode-Design Web
]

[elasticsearch]
# endpoint = ["http://localhost:9201", "http://localhost:9200"]
endpoint = ["http://localhost:9200"]
index = "ink"


[archivestrategy]
    "2641719" = "single"

[zotero]
    endpoint = "https://api.zotero.org"
    apikey = "QWd1IDWGnLzwG9fBIZbXyXL4"
    [zotero.database]
        servertype = "postgres"
        dsn = "postgres://zotero:zZLOpCuHylgRATkCnNL0@localhost:5433/zotero"
        connection_max = 5000
        schema = "s3"

[s3]
    endpoint = "minio.campusderkuenste.ch"
    accessKeyId = "zotero"
    secretAccessKey = "zXbJKxnYZP708Ni84Lep"
    useSSL = true



[mediaserver]
    url = "https://ba14ns21403-sec1.fhnw.ch/mediasrv"
    [mediaserver.database]
        servertype = "mysql"
        # dsn = "mediaserver:secret@tcp(v000306.adm.ds.fhnw.ch:3306)/mediaserver?charset=utf8"
        dsn = "mediaserver:kn6Iy4mLuzH7HWPo@tcp(localhost:3306)/mediaserver?charset=utf8"
        connection_max = 5000
        schema = "mediaserver"

[fairservice]
    servicename = "FairService"
    #address = "https://localhost:8443/mediathek"
    address = "https://dataverse.hgk.fhnw.ch/mediathek"
    certskipverify = true
    jwtkey = "ov@cO+Rn,lcwmP6r:O3"
    jwtalg = "HS512"

[zsearchservice]
    servicename = "ZSearch"
    #address = "https://localhost:443/api"
    address = "https://mediathek.hgk.fhnw.ch/amp/api"
    certskipverify = true
    #jwtkey = "geheim"
    jwtkey = ":Xf/#|IKYrDsNi4]LN*o(W7;:"
    jwtalg = "HS512"


[_tunnel.ba14ns21403]
    user = "root"
    privatekey = "C:/daten/keys/putty_ed25519.priv.openssh"
    [_tunnel.ba14ns21403.endpoint]
        port = 22
        host = "ba14ns21403.fhnw.ch"
    # postgres
    [_tunnel.ba14ns21403.forward.postgres.local]
        port = 5433
        host = "localhost"
    [_tunnel.ba14ns21403.forward.postgres.remote]
        port = 5432
        host = "v000306.adm.ds.fhnw.ch"
    # elasticsearch
    [_tunnel.ba14ns21403.forward.elasticsearch.local]
        port = 9200
        host = "localhost"
    [_tunnel.ba14ns21403.forward.elasticsearch.remote]
        port = 9200
        host = "asara269.adm.ds.fhnw.ch"
    # mysql
    [_tunnel.ba14ns21403.forward.mysql.local]
        port = 3306
        host = "localhost"
    [_tunnel.ba14ns21403.forward.mysql.remote]
        port = 3306
        host = "v000306.adm.ds.fhnw.ch"
