servicename = "ZSearch"
logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
accesslog = "" # http access log file
addr = "localhost:8443"
#addrext = "https://mediathek.hgk.fhnw.ch/amp/"
addrext = "https://localhost:8443/"
certpem = "auto"
#certpem = "cert/server.crt" # tls zsearchclient certificate file in PEM format
#keypem = "cert/server.key" # tls zsearchclient key file in PEM format
#staticdir = "C:/daten/go/dev/zsearch/web/static/"
sitemapdir = "C:/daten/go/dev/zsearch/web/static/"
#templatedir = "C:/daten/go/dev/zsearch/web/template/"
#staticcachecontrol = "max-age=2592000, s-maxage=864000, stale-while-revalidate=86400, public"
staticcachecontrol = "max-age=31968000, s-maxage=864000, stale-while-revalidate=86400, public"
collectionscatalog = "allcollections"
clustercatalog = "cluster"
#jwtkey = "geheim"
jwtkey = ":Xf/#|IKYrDsNi4]LN*o(W7;:"
jwtalg = ["HS256","HS384","HS512"]
linktokenexp = "1h"
loginurl = "https://intern.hgk.fhnw.ch/ango/shib/auth/localhost"
loginissuer = "auth.hgk.fhnw.ch/localhost"
idletimeout = "30m"
sessiontimeout = "45m"
usercachesize = 200
mediaserver = "https://ba14ns21403-sec1.fhnw.ch/mediasrv"
mediaserverkey = "sdfsdafsdfsdfsd"
mediaserverexp = "6h"
ampcache = ""
ampapikey = "C:/daten/go/dev/zsearch/configs/amp.private-key.pem"
cachedir = "C:/temp/badger"
cacheexpiry = "3h"
clearcacheonstartup = true # remove badger files from cachedir
templatedev = true
instancename = "Mediathek HGK"
facebookappid = "1102189490244305"

[prefix]
    detail = "/detail"
    update = "/update"
    search = "/search"
    collections = "/collections"
    cse = "/cse"
    cluster = "/cluster"
    api = "/api"
    static = "/static"
    sitemap = "/sitemap"
    images = "/images"


[target]
elasticindex = "fhnw_ink_test" # elastic search index to fill
elasticindexcreate = "./configdata/schema.v8.json" # deletes and creates elastic index with given schema
#elasticindexcreate = "/mnt/c/daten/go/dev/alma2elastic/elastic/schema_core_non-dynamic.json" # deletes and creates elastic index with given schema
elasticendpoint = "https://elastic.med.campusderkuenste.ch/" # endpoint for elastic search
elasticapikey = "NktZTk1vb0JVcWJ2SHE1Sk5iLXo6TEY3aU9jWnVTX0dpTVdOWm41WkNBZw=="
elasticv8 = true # use elastic search client version 8

[_sshtunnel]
    user = "root"
    privatekey = "C:/daten/keys/putty_ed25519.priv.openssh"
    [sshtunnel.serverendpoint]
        port = 22
        host = "ba14ns21403.fhnw.ch"

    [sshtunnel.localendpoint]
        port = 9202
        host = "localhost"

    [sshtunnel.remoteendpoint]
        port = 9200
        host = "asara269.adm.ds.fhnw.ch"

[elasticsearch]
    # endpoint = ["http://localhost:9201", "http://localhost:9200"]
    endpoint = ["https://elastic.med.campusderkuenste.ch/"]
    index = "fhnw_ink_test"
    apikey = "NktZTk1vb0JVcWJ2SHE1Sk5iLXo6TEY3aU9jWnVTX0dpTVdOWm41WkNBZw=="

[icons]
    journalarticle = "#ion-document-text-outline"
    book = "#ion-browsers-rotate-90"
    audiorecording = "#ion-mic-outline"
    videorecording = "#ion-videocam-outline"
    conferencepaper = "#ion-document-text-outline"
    document = "#ion-browsers"
    thesis = "#ion-school-outline"
    booksection = "#chrome-reader-mode-black"
    project = "#ion-browsers"
    presentation = "#ion-easel-outline"
    reference = "#ion-open-outline"

[[locations]]
    group = "location/fhnw"
    networks = ["10.0.0.0/8", "192.168.0.0/16", "147.86.0.0/16"]

[[locations]]
    group = "location/memoriav"
    networks = ["62.2.199.158/32"]

[searchfields]
    # __Q__ will be replaced by search term
    author = "persons.name.keyword"
    tag = "tags.keyword"
    cat = "category" #"category.keyword"
    catalog = "catalog.keyword"
    source = "source.keyword"
    date = "date.keyword"

[access]
    admin = "localhost/admin"
    guest = "global/guest"

[query]
    basecatalog = ["mediathek"]
    # basefilter = "source:zotero OR source:diplomhgk"
    [[query.subfilter]]
        label = "hgkfotos"
        name = "Fotoarchiv HGK"
        filter = "catalog:hgkfotos"
    [[query.subfilter]]
        label = "diplomhgk"
        name = "Diplomarchiv HGK"
        filter = "source:diplomhgk"

[google]
    apikey = "AIzaSyBfYHNyyspnojxDzqhpRuAMy5bQQ-iNwDE"
#    [google.searchkeys.mediathek]
#        key = "013219768911029609903:u7pzivy74dt"
#        name = "Mediathek"
    [google.searchkeys.education]
        key = "3dded773a55aff88a"
        name = "Bildung"
    [google.searchkeys.academies]
        name = "Academies"
        key = "1d2533143713fcf1b"
    [google.searchkeys.research]
        key = "724d60bccee7a40eb"
        name = "Forschung"
    [google.searchkeys.sustainability]
        key = "f6f5623c8c57e6e6e"
        name = "Nachhaltigkeit"
    [google.searchkeys.diversity]
        key = "13f71a822f1bc310f"
        name = "Diversität"
    [google.searchkeys.knowledge]
        key = "7d0e9ad38c17560d6"
        name = "Wissen"
    # [google.searchkeys.infrastructures]
    #     key = "3e9a009cab56daf82"
    #     name = "Infrastrukturen"
    # [google.searchkeys.spaces]
    #     key = "6aaef2b40d49cc922"
    #     name = "Räume"
    [google.searchkeys.products]
        key = "b091ba23cc1c744e1"
        name = "Produkte"
    [google.searchkeys.practice]
        key = "92a9e2fd108a59fb7"
        name = "Praxis"

[[facets]]
	Name = "mediatype"
	Field = "mediatype"
	#Query = ""
	Prefix = ""
    Type = "terms"
	[facets.restrict]
	    video = false
	    audio = false
	    image = false
	    pdf = false
	    

[template]
    "embedVideo.gohtml" = [
        "embedVideo.gohtml",
    ]
    "details.amp.gohtml" = [
        "css/gsearch.inc.min.css",
        "css/darkmode.inc.min.css",
        "css/lightmode.inc.min.css",
        "css/headings.inc.min.css",
        "css/buttons.inc.min.css",
        "css/commerce.inc.min.css",
        "css/table.inc.min.css",
        "css/col.inc.min.css",
        "css/text.inc.min.css",
        "css/flexbox.inc.min.css",
        "css/padding.inc.min.css",
        "css/margin.inc.min.css",
        "css/main.inc.min.css",
        "css/inter.inc.min.css", "css/social.inc.min.css",
        "ionicons.inc.gohtml",
        "navbar.inc.gohtml",
        "header.inc.gohtml",
        "footer.inc.gohtml",
        "details.media.inc.gohtml",
        "details.media.prefetch.inc.gohtml",
        "searchcontent.inc.gohtml",
        "details.amp.gohtml",
        "logo.svg",
        ]
    "error.gohtml" = ["error.gohtml"]
"forbidden.amp.gohtml" = [
    "css/gsearch.inc.min.css",
    "css/darkmode.inc.min.css",
    "css/lightmode.inc.min.css",
    "css/headings.inc.min.css",
    "css/buttons.inc.min.css",
    "css/commerce.inc.min.css",
    "css/table.inc.min.css",
    "css/col.inc.min.css",
    "css/text.inc.min.css",
    "css/flexbox.inc.min.css",
    "css/padding.inc.min.css",
    "css/margin.inc.min.css",
    "css/main.inc.min.css",
    "css/inter.inc.min.css", "css/social.inc.min.css",

    "navbar.inc.gohtml",
    "header.inc.gohtml",
    "footer.inc.gohtml",
    "forbidden.amp.gohtml",
    "logo.svg",
]
"error.amp.gohtml" = [
    "css/gsearch.inc.min.css",
    "css/darkmode.inc.min.css",
    "css/lightmode.inc.min.css",
    "css/headings.inc.min.css",
    "css/buttons.inc.min.css",
    "css/commerce.inc.min.css",
    "css/table.inc.min.css",
    "css/col.inc.min.css",
    "css/text.inc.min.css",
    "css/flexbox.inc.min.css",
    "css/padding.inc.min.css",
    "css/margin.inc.min.css",
    "css/main.inc.min.css",
    "css/inter.inc.min.css", "css/social.inc.min.css",

    "navbar.inc.gohtml",
    "header.inc.gohtml",
    "footer.inc.gohtml",
    "error.amp.gohtml",
    "logo.svg",
]
"search.amp.gohtml" = [
    "css/gsearch.inc.min.css",
    "css/darkmode.inc.min.css",
    "css/lightmode.inc.min.css",
    "css/headings.inc.min.css",
    "css/buttons.inc.min.css",
    "css/commerce.inc.min.css",
    "css/table.inc.min.css",
    "css/col.inc.min.css",
    "css/text.inc.min.css",
    "css/flexbox.inc.min.css",
    "css/padding.inc.min.css",
    "css/margin.inc.min.css",
    "css/main.inc.min.css",
    "css/inter.inc.min.css", "css/social.inc.min.css",

    "ionicons.inc.gohtml",
    "navbar.inc.gohtml",
    "header.inc.gohtml",
    "footer.inc.gohtml",
    "searchNav.inc.gohtml",
    "searchcontent.inc.gohtml",
    "search.amp.gohtml",
    "logo.svg",
]
"cluster.amp.gohtml" = [
    "css/gsearch.inc.min.css",
    "css/darkmode.inc.min.css",
    "css/lightmode.inc.min.css",
    "css/headings.inc.min.css",
    "css/buttons.inc.min.css",
    "css/commerce.inc.min.css",
    "css/table.inc.min.css",
    "css/col.inc.min.css",
    "css/text.inc.min.css",
    "css/flexbox.inc.min.css",
    "css/padding.inc.min.css",
    "css/margin.inc.min.css",
    "css/main.inc.min.css",
    "css/inter.inc.min.css", "css/social.inc.min.css",
    "ionicons.inc.gohtml",
    "navbar.inc.gohtml",
    "header.inc.gohtml",
    "footer.inc.gohtml",
    "searchNav.inc.gohtml",
    "cluster.amp.gohtml",
    "logo.svg",
]
"google.amp.gohtml" = [
    "css/gsearch.inc.min.css",
    "css/darkmode.inc.min.css",
    "css/lightmode.inc.min.css",
    "css/headings.inc.min.css",
    "css/buttons.inc.min.css",
    "css/commerce.inc.min.css",
    "css/table.inc.min.css",
    "css/col.inc.min.css",
    "css/text.inc.min.css",
    "css/flexbox.inc.min.css",
    "css/padding.inc.min.css",
    "css/margin.inc.min.css",
    "css/main.inc.min.css",
    "css/inter.inc.min.css", "css/social.inc.min.css",
    "ionicons.inc.gohtml",
    "navbar.inc.gohtml",
    "header.inc.gohtml",
    "footer.inc.gohtml",
    "searchNav.inc.gohtml",
    "google.amp.gohtml",
    "logo.svg",
]
    "collections.amp.gohtml" = [
        "css/gsearch.inc.min.css",
        "css/darkmode.inc.min.css",
        "css/lightmode.inc.min.css",
        "css/headings.inc.min.css",
        "css/buttons.inc.min.css",
        "css/commerce.inc.min.css",
        "css/table.inc.min.css",
        "css/col.inc.min.css",
        "css/text.inc.min.css",
        "css/flexbox.inc.min.css",
        "css/padding.inc.min.css",
        "css/margin.inc.min.css",
        "css/main.inc.min.css",
        "css/inter.inc.min.css", "css/social.inc.min.css",

        "ionicons.inc.gohtml",
        "css/darkmode.inc.min.css",
        "css/lightmode.inc.min.css",
        "navbar.inc.gohtml",
        "header.inc.gohtml",
        "footer.inc.gohtml",
        "searchNav.inc.gohtml",
        "collections.prefetch.inc.gohtml",
        "collections.amp.gohtml",
        "logo.svg",
    ]
    "clusterall.amp.gohtml" = [
        "css/gsearch.inc.min.css",
        "css/darkmode.inc.min.css",
        "css/lightmode.inc.min.css",
        "css/headings.inc.min.css",
        "css/buttons.inc.min.css",
        "css/commerce.inc.min.css",
        "css/table.inc.min.css",
        "css/col.inc.min.css",
        "css/text.inc.min.css",
        "css/flexbox.inc.min.css",
        "css/padding.inc.min.css",
        "css/margin.inc.min.css",
        "css/main.inc.min.css",
        "css/inter.inc.min.css", "css/social.inc.min.css",
        "ionicons.inc.gohtml",
        "css/darkmode.inc.min.css",
        "css/lightmode.inc.min.css",
        "navbar.inc.gohtml",
        "header.inc.gohtml",
        "footer.inc.gohtml",
        "searchNav.inc.gohtml",
        "clusterall.prefetch.inc.gohtml",
        "clusterall.amp.gohtml",
        "logo.svg",
    ]
    "imagesearch.amp.gohtml" = [
        "css/gsearch.inc.min.css",
        "css/darkmode.inc.min.css",
        "css/lightmode.inc.min.css",
        "css/headings.inc.min.css",
        "css/buttons.inc.min.css",
        "css/commerce.inc.min.css",
        "css/table.inc.min.css",
        "css/col.inc.min.css",
        "css/text.inc.min.css",
        "css/flexbox.inc.min.css",
        "css/padding.inc.min.css",
        "css/margin.inc.min.css",
        "css/main.inc.min.css",
        "css/inter.inc.min.css", "css/social.inc.min.css",
        "ionicons.inc.gohtml",
        "navbar.inc.gohtml",
        "header.inc.gohtml",
        "footer.inc.gohtml",
        "searchNav.inc.gohtml",
        "imagesearch.amp.gohtml",
        "logo.svg",
        ]
